### ISSUE TITLE
Issues found during the setup

### ISSUE THREAD

**Issue by criostage** [LeGeRyChEeSe/Sunshine-AIO#10]
Today i was given this repo by a friend of a friend, after me complaining about not being able to setup sunshine propertly in my setup. During the setup on my gaming rig I encountered some issues ... The issue was whenever I attempt to connect to my Sunshine instance configured to use Sunshine-AIO, it would just time out with errors, but after (maybe a little too much) of troubleshooting i was able to make it finally work!

I understand that somethings may not be related to this project but maybe someone with the same issue can find the resolutions in this github issue and/or it can contribute to the documentation. Here's a list of what went wrong and how i fixed it:

1. **Issue** The Virtual Display Driver (23.12.2 HDR, Windows 11 22H2+) didn't worked for me: Every time i installed it, windows would complain about not being able to load the driver. I followed the instructions and "Installed"/copied the **IddSampleDriver** folder to the root of the C Drive, but no joy.. rebooted my gaming device multiple times, reinstalled the driver but nothing would made it work...

 **Solution**: Ended up looking into the Virtual Display Driver repo and found a Beta Driver, tested it and this made the display "looking normal" in the device manager (windows loaded the driver successfully). After this i was able to follow with the guide and disabled the display.

2. **Issue** The execution policy in powershell when running the **do** and **undo** scripts from sunshine: i know in the documentation states that we need to change it to install the module, but i always use the following to change the execution policy temporarily: **Set-ExecutionPolicy bypass -scope process**. This will change the execution policy but not permentantly, so when i close the window where i executed that command the execution policy will go back to the default. So in a way it worked fine during the installation of the **Sunshine Virtual Monitor WindowsDisplayManager module** but had issues down the line when i tried to run the scripts from Sunshine Command Preparations. 

**Solution**, changed the command line (the output giventhe script executed on the **sunshine setup** step) from step to include the **-executionpolicy bypass**  parameter, example: _cmd /C powershell.exe **-ExecutionPolicy bypass** -File C:\sunshine-virtual-monitor-main\setup_sunvdm.ps1 %SUNSHINE_CLIENT_WIDTH% %SUNSHINE_CLIENT_HEIGHT% %SUNSHINE_CLIENT_FPS% %SUNSHINE_CLIENT_HDR% > C:\sunshine-virtual-monitor-main\sunvdm.log 2>&1_. This will make that every time the script is executed sunshine I will always run it with the execution policy set to bypass without changing the policy on the entire machine. Did this for both **do** and **undo**.

3. **Issue**: The script exiting with code error [1]: 
**Solution** this was a rather easy one... i saw this on another issue in the github tracker, where all I had to do was to remove the "mark of the web" on the downloaded zip or on the extracted files.

4. **Issue** Error on the setup_sunvdm.ps1 powershell script that exited with the error "_Failed to disable all other displays. At C:\sunshine-virtual-monitor-main\setup_sunvdm.ps1:74 char:9_".
**Solution**: This one was a little tricker to find, but only because i had to troubleshoot the script it self. Ended up finding that a condition had a string that was not matching with the driver's description. This can be found on the lines 43, 49 and 83 and replacing the keyworks **IddSampleDriver Device HDR** with **Virtual Display with HDR** did the trick. Maybe this is not applicable to everyone and a consequence of using the beta driver? But if it's in the Beta Driver, maybe when it comes as a full release it will ship with this small change ....

So this was it, after making all of this was able to finally make it work!
Hope this helps anyone out there

**Comment by criostage** [comment]
Just a small update, each driver available has a different description. I retried using the stable driver and used the one without HDR.. it worked as the beta driver. and again I had to change the detection on the script to search for the driver that has "Virtual Display Driver by MTT" in the description.

**Comment by LeGeRyChEeSe** [comment]
Hello, thanks for all the tests. It will help me a lot to improve the script to fit as many configuration as possible. I think i'll check the sunshine virtual monitor repo and make some code readjustment to fit perfectly my needs.
