### ISSUE TITLE
Install will stall if spaces are present in the path to Sunshine-AIO.exe.

### ISSUE THREAD

**Issue by jreynolds72** [LeGeRyChEeSe/Sunshine-AIO#17]
I noticed today when attempting to run Sunshine-AIO that if there are any spaces in the path leading to the executable, the sunshine installer stalls (See Screenshot).  I closed the sunshine installer, and the script proceeded installing the other components.  After changing the space to a -, the sunshine installer installed as expected.

I wonder if the path passed to the sunshine installer can be enclosed in quotes to allow spaces?  Not a big deal for me but I thought I'd mention if others run into this issue.

![Screenshot 2024-09-14 at 1 16 45 PM](https://github.com/user-attachments/assets/005a732c-5575-467e-80c0-496da20d4324)

**Comment by LeGeRyChEeSe** [comment]
Hello, thanks for your feedback. It’s a known issue. It should be fixed in next release.

**Comment by LeGeRyChEeSe** [comment]
A workaround has been applied so now you can't execute the script if there is spaces in the path.
