### ISSUE TITLE
shutdown display

### ISSUE THREAD

**Issue by darkjezza** [LeGeRyChEeSe/Sunshine-AIO#18]
Hi so when I shut down my computer when the streams still on my displays don't turn on until I stream again and exit that way is there a way to solve this issue?

Can I some how make my monitors connect on windows 11 bootup

**Comment by darkjezza** [comment]
Got another problem with multiple monitors only the primary screen turns back on the others excluding virtual are disconnected

**Comment by ezemacchi** [comment]
hi! I'm having the same problem, I am going to try to add the scripts, "setup_sunvdm.ps1" and "teardown_sunvdm.ps1" to the App  Lunch config_up, instead usign the global config

My idea is to using only Steam Big Picture, with those scripts, and add another app that run a power down script

other way could be changing or adding an internal task when windows is being shutdown, like, if driver IDDSample is active, deactivate, and active the "original" one.

perhaps someone has better ideas than me
I will try change the config to run only for Steam Big Picture, and add another "app" to shootdown the pc from moonlight

**Comment by LeGeRyChEeSe** [comment]
Hello, this is not a Sunshine AIO related issue. You can ask in Sunshine Virtual Monitor github project.
