### ISSUE TITLE
Unable to download Virtual Display Driver?

### ISSUE THREAD

**Issue by fluffthetail** [LeGeRyChEeSe/Sunshine-AIO#23]
It is repeatedly failing to download the virtual display driver. Any ideas what's going on?
![image](https://github.com/user-attachments/assets/6a946a0c-35c5-434b-9d68-de729c016815)

**Comment by LeGeRyChEeSe** [comment]
Hello, please download and install VDD manually until i update the code for the AIO because new VDD updates breaks my code (different names used for packages)

**Comment by LeGeRyChEeSe** [comment]
The new release resolved the issue.
